### ISSUE TITLE
RuntimeError when run idqn, vdn, qmix?

### ISSUE THREAD

**Issue by bradley-code-again** [koulanurag/minimal-marl#4]
Hi when I run python idqn.py, or vdn.py or qmix.py, there is a rumtime error.
"RuntimeError: cannot perform reduction function argmax on a tensor with no elements because the operation does not have an identity"
It is caused by "action[~mask] = out[~mask].argmax(dim=2).float()", I suppose it is because out[~mask] is empty when mask=True.
Please have a look, thanks.

**Comment by koulanurag** [comment]
Hi @bradley-code-again ,

Thanks for raising this issue. I tried to replicate your mentioned concerns. However, it seems to work in either case of masks.

**Case 1: mask is True**

```python console
>>> import torch
>>> torch.__version__
'1.9.0+cu102'
>>> epsilon = 1.1 # Thereby mask will be True 
>>> out = torch.rand((1,2,5))
>>> out
tensor([[[0.9265, 0.5606, 0.5753, 0.8355, 0.6015],
         [0.8950, 0.8526, 0.6406, 0.7169, 0.2929]]])
>>> mask = (torch.rand((out.shape[0],)) <= epsilon)
>>> mask
tensor([True])
>>> action = torch.empty((out.shape[0], out.shape[1],))
>>> action
tensor([[3.2604e-12, 1.7743e+28]])
>>> action[mask] = torch.randint(0, out.shape[2], action[mask].shape).float()
>>> action
tensor([[4., 3.]])
>>> action[~mask] = out[~mask].argmax(dim=2).float()
>>> action
tensor([[4., 3.]])
```

**Case 2 : mask is False**

```python console
>>> epsilon = -1 # Thereby mask will be always False
>>> mask = (torch.rand((out.shape[0],)) <= epsilon)
>>> mask
tensor([False])
>>> action = torch.empty((out.shape[0], out.shape[1],))
>>> action
tensor([[4.9082e-37, 0.0000e+00]])
>>> action[mask] = torch.randint(0, out.shape[2], action[mask].shape).float()
>>> action
tensor([[4.9082e-37, 0.0000e+00]])
>>> action[~mask] = out[~mask].argmax(dim=2).float()
>>> action
tensor([[4., 3.]])
```
Please, let me know if you still face this error. **Also, please ensure that you have the required PyTorch dependency.**

**Comment by seolhokim** [comment]
This error also occurs to me. my torch version is 1.8.1.

`action[~mask] = out[~mask].argmax(dim=2).float()` doesn't work like you.

**Comment by koulanurag** [comment]
@seolhokim  Thanks for raising this issue again!  I would suggest updating `torch`  to  `>=1.9.0` as this is the version in previous comment of mine. In the meanwhile, I am going to look again into this issue.

**Comment by bradley-code-again** [comment]
Hi, it is working with torch==1.9.0, and sorry for back to you after so long.
